from .metrics.audacity import (
    check_audio_duration,
    check_audio_sample_rate,
    check_audio_channels,
    check_audio_rms_level,
    check_audio_fade_in,
    check_audio_fade_out,
    check_audio_silence_at,
    check_audio_has_content_at,
    check_audio_peak_amplitude,
    check_audio_file_valid,
    check_audio_properties,
    check_audio_with_fades,
    check_audio_duration_range,
    check_aup3_track_count,
    check_aup3_track_gain,
    check_aup3_track_mute,
    check_aup3_labels,
    check_aup3_project_valid,
    check_interactive_audacity_ia01,
    check_interactive_audacity_ia02,
    check_interactive_audacity_ia03,
    check_interactive_audacity_ia04,
    check_interactive_audacity_ia05,
)

from .metrics.blender import (
    check_blender_object_exists,
    check_blender_object_deleted,
    check_blender_object_count,
    check_blender_object_location,
    check_blender_object_scale,
    check_blender_object_rotation,
    check_blender_object_renamed,
    check_blender_object_visibility,
    check_blender_light_type,
    check_blender_light_energy,
    check_blender_render_settings,
    check_blender_animation_range,
    check_blender_collection_exists,
    check_blender_object_in_collection,
    check_blender_text_content,
    check_blender_material_pbr,
    check_blender_modifier_boolean,
    check_blender_texture_assigned,
    check_blender_modifier_stack,
    check_blender_world_hdri,
    check_blender_animation_keyframes,
    check_blender_parent_child,
    check_blender_collection_members,
    check_blender_constraints_multi,
    check_blender_applied_modifier,
    check_blender_smooth_shading,
    check_blender_particle_params,
    check_blender_selective_smooth,
    check_blender_animation_extended,
    check_blender_collection_organization,
    check_blender_hierarchy,
    check_blender_multi_light_config,
    check_blender_text_styling,
    check_blender_material_textures,
    check_blender_follow_path,
    check_blender_modifier_order,
    check_blender_transform_applied,
    check_blender_mesh_bounds,
    check_blender_render_output,
    check_blender_render_video,
    check_blender_multi_material_scene,
    check_blender_scene_objects,
    check_blender_material_color,
    check_blender_camera_config,
    check_blender_modifier_subsurf,
    check_blender_render_engine,
    check_blender_frame_range,
    check_blender_fps,
    check_blender_mesh_modified,
    check_blender_modifier_bevel,
    check_blender_pbr_setup,
)

from .metrics.inkscape import (
    check_inkscape_fill_color,
    check_inkscape_stroke,
    check_inkscape_element_geometry,
    check_inkscape_text_content,
    check_inkscape_text_style,
    check_inkscape_layer_visibility,
    check_inkscape_layer_name,
    check_inkscape_element_deleted,
    check_inkscape_document_properties,
    check_inkscape_opacity,
    check_inkscape_element_count,
    check_inkscape_text_align,
    check_inkscape_add_layer,
    check_inkscape_ungroup,
    check_inkscape_zorder,
    check_inkscape_stroke_dasharray,
    check_inkscape_stroke_linecap,
    check_inkscape_radial_gradient,
    check_inkscape_transform,
    check_inkscape_align,
    check_inkscape_object_to_path,
    check_inkscape_fill_rule,
    check_inkscape_snap_to_grid,
    # New atomic functions (L2/L3)
    check_inkscape_filter,
    check_inkscape_boolean_operation,
    check_inkscape_gradient,
    check_inkscape_clone_exists,
    check_inkscape_layer_order,
    check_inkscape_group_children,
    check_inkscape_layer_lock,
    check_inkscape_export_file_exists,
    # L2 composite evaluators
    check_inkscape_l2_boolean_restyle,
    check_inkscape_l2_boolean_move,
    check_inkscape_l2_blur_opacity,
    check_inkscape_l2_clone_restyle,
    check_inkscape_l2_gradient_shadow,
    check_inkscape_l2_multi_transform,
    check_inkscape_l2_layer_ops,
    check_inkscape_l2_group_transform,
    check_inkscape_l2_path_stroke,
    check_inkscape_l2_scale_guide,
    check_inkscape_l2_shadow_zorder,
    # L3 composite evaluators
    check_inkscape_infographic_rebrand,
    check_inkscape_icon_composition,
    check_inkscape_boolean_pipeline,
    check_inkscape_layer_workflow,
    check_inkscape_complex_path_workflow,
    check_inkscape_full_poster_workflow,
    check_inkscape_shape_composition_workflow,
    check_inkscape_dashboard_surgery,
    check_inkscape_tiled_pattern_workflow,
    check_inkscape_dual_export_poster,
    # Inkscape interactive evaluators
    check_interactive_inkscape_ii01,
    check_interactive_inkscape_ii02,
    check_interactive_inkscape_ii03,
    check_interactive_inkscape_ii04,
    check_interactive_inkscape_ii05,
    check_interactive_inkscape_ii06,
)

from .metrics.new_gimp import (
    check_045bf3ff_brightness_increase,
    check_045bf3ff_invert,
    check_045bf3ff_grayscale,
    check_045bf3ff_jpeg_export,
    check_045bf3ff_rotation,
    check_045bf3ff_png_format,
    check_045bf3ff_text_add,
    check_7b7617bd_undo_levels,
    check_7b7617bd_recent_files,
    check_8ea73f6f_resize_1920x1080,
    check_fbb548ca_blue_border,
    check_f4aec372_text_triangle,
    check_d16c99dc_resize_layer_800,
    check_d16c99dc_center_crop_400x400,
    check_d16c99dc_resize_600_jpg,
    check_d16c99dc_duplicate_resize_rename,
    check_d16c99dc_crop_500x500_topleft,
    check_d16c99dc_opacity_and_layer_order,
    check_b148e375_new_layer_circle,
    check_b148e375_duplicate_rename_hide,
    check_b148e375_resize_50_percent,
    check_b148e375_rect_select_fill_red,
    check_554785e9_saturation_increase_40,
    check_7767eef2_text_copyright,
    check_734d6579_green_background,
)

eval_funcs = {
    # Audacity evaluators
    "check_audio_duration": check_audio_duration,
    "check_audio_sample_rate": check_audio_sample_rate,
    "check_audio_channels": check_audio_channels,
    "check_audio_rms_level": check_audio_rms_level,
    "check_audio_fade_in": check_audio_fade_in,
    "check_audio_fade_out": check_audio_fade_out,
    "check_audio_silence_at": check_audio_silence_at,
    "check_audio_has_content_at": check_audio_has_content_at,
    "check_audio_peak_amplitude": check_audio_peak_amplitude,
    "check_audio_file_valid": check_audio_file_valid,
    "check_audio_properties": check_audio_properties,
    "check_audio_with_fades": check_audio_with_fades,
    "check_audio_duration_range": check_audio_duration_range,
    "check_aup3_track_count": check_aup3_track_count,
    "check_aup3_track_gain": check_aup3_track_gain,
    "check_aup3_track_mute": check_aup3_track_mute,
    "check_aup3_labels": check_aup3_labels,
    "check_aup3_project_valid": check_aup3_project_valid,
    "check_interactive_audacity_ia01": check_interactive_audacity_ia01,
    "check_interactive_audacity_ia02": check_interactive_audacity_ia02,
    "check_interactive_audacity_ia03": check_interactive_audacity_ia03,
    "check_interactive_audacity_ia04": check_interactive_audacity_ia04,
    "check_interactive_audacity_ia05": check_interactive_audacity_ia05,
    # Inkscape evaluators
    "check_inkscape_fill_color": check_inkscape_fill_color,
    "check_inkscape_stroke": check_inkscape_stroke,
    "check_inkscape_element_geometry": check_inkscape_element_geometry,
    "check_inkscape_text_content": check_inkscape_text_content,
    "check_inkscape_text_style": check_inkscape_text_style,
    "check_inkscape_layer_visibility": check_inkscape_layer_visibility,
    "check_inkscape_layer_name": check_inkscape_layer_name,
    "check_inkscape_element_deleted": check_inkscape_element_deleted,
    "check_inkscape_document_properties": check_inkscape_document_properties,
    "check_inkscape_opacity": check_inkscape_opacity,
    "check_inkscape_element_count": check_inkscape_element_count,
    "check_inkscape_text_align": check_inkscape_text_align,
    "check_inkscape_add_layer": check_inkscape_add_layer,
    "check_inkscape_ungroup": check_inkscape_ungroup,
    "check_inkscape_zorder": check_inkscape_zorder,
    "check_inkscape_stroke_dasharray": check_inkscape_stroke_dasharray,
    "check_inkscape_stroke_linecap": check_inkscape_stroke_linecap,
    "check_inkscape_radial_gradient": check_inkscape_radial_gradient,
    "check_inkscape_transform": check_inkscape_transform,
    "check_inkscape_align": check_inkscape_align,
    "check_inkscape_object_to_path": check_inkscape_object_to_path,
    "check_inkscape_fill_rule": check_inkscape_fill_rule,
    "check_inkscape_snap_to_grid": check_inkscape_snap_to_grid,
    # Inkscape new atomic functions (L2/L3)
    "check_inkscape_filter": check_inkscape_filter,
    "check_inkscape_boolean_operation": check_inkscape_boolean_operation,
    "check_inkscape_gradient": check_inkscape_gradient,
    "check_inkscape_clone_exists": check_inkscape_clone_exists,
    "check_inkscape_layer_order": check_inkscape_layer_order,
    "check_inkscape_group_children": check_inkscape_group_children,
    "check_inkscape_layer_lock": check_inkscape_layer_lock,
    "check_inkscape_export_file_exists": check_inkscape_export_file_exists,
    # Inkscape L2 composite evaluators
    "check_inkscape_l2_boolean_restyle": check_inkscape_l2_boolean_restyle,
    "check_inkscape_l2_boolean_move": check_inkscape_l2_boolean_move,
    "check_inkscape_l2_blur_opacity": check_inkscape_l2_blur_opacity,
    "check_inkscape_l2_clone_restyle": check_inkscape_l2_clone_restyle,
    "check_inkscape_l2_gradient_shadow": check_inkscape_l2_gradient_shadow,
    "check_inkscape_l2_multi_transform": check_inkscape_l2_multi_transform,
    "check_inkscape_l2_layer_ops": check_inkscape_l2_layer_ops,
    "check_inkscape_l2_group_transform": check_inkscape_l2_group_transform,
    "check_inkscape_l2_path_stroke": check_inkscape_l2_path_stroke,
    "check_inkscape_l2_scale_guide": check_inkscape_l2_scale_guide,
    "check_inkscape_l2_shadow_zorder": check_inkscape_l2_shadow_zorder,
    # Inkscape L3 composite evaluators
    "check_inkscape_infographic_rebrand": check_inkscape_infographic_rebrand,
    "check_inkscape_icon_composition": check_inkscape_icon_composition,
    "check_inkscape_boolean_pipeline": check_inkscape_boolean_pipeline,
    "check_inkscape_layer_workflow": check_inkscape_layer_workflow,
    "check_inkscape_complex_path_workflow": check_inkscape_complex_path_workflow,
    "check_inkscape_full_poster_workflow": check_inkscape_full_poster_workflow,
    "check_inkscape_shape_composition_workflow": check_inkscape_shape_composition_workflow,
    "check_inkscape_dashboard_surgery": check_inkscape_dashboard_surgery,
    "check_inkscape_tiled_pattern_workflow": check_inkscape_tiled_pattern_workflow,
    "check_inkscape_dual_export_poster": check_inkscape_dual_export_poster,
    # Inkscape interactive evaluators
    "check_interactive_inkscape_ii01": check_interactive_inkscape_ii01,
    "check_interactive_inkscape_ii02": check_interactive_inkscape_ii02,
    "check_interactive_inkscape_ii03": check_interactive_inkscape_ii03,
    "check_interactive_inkscape_ii04": check_interactive_inkscape_ii04,
    "check_interactive_inkscape_ii05": check_interactive_inkscape_ii05,
    "check_interactive_inkscape_ii06": check_interactive_inkscape_ii06,
    # GIMP evaluators
    "check_045bf3ff_brightness_increase": check_045bf3ff_brightness_increase,
    "check_045bf3ff_invert": check_045bf3ff_invert,
    "check_045bf3ff_grayscale": check_045bf3ff_grayscale,
    "check_045bf3ff_jpeg_export": check_045bf3ff_jpeg_export,
    "check_045bf3ff_rotation": check_045bf3ff_rotation,
    "check_045bf3ff_png_format": check_045bf3ff_png_format,
    "check_045bf3ff_text_add": check_045bf3ff_text_add,
    "check_7b7617bd_undo_levels": check_7b7617bd_undo_levels,
    "check_7b7617bd_recent_files": check_7b7617bd_recent_files,
    "check_8ea73f6f_resize_1920x1080": check_8ea73f6f_resize_1920x1080,
    "check_fbb548ca_blue_border": check_fbb548ca_blue_border,
    "check_f4aec372_text_triangle": check_f4aec372_text_triangle,
    "check_d16c99dc_resize_layer_800": check_d16c99dc_resize_layer_800,
    "check_d16c99dc_center_crop_400x400": check_d16c99dc_center_crop_400x400,
    "check_d16c99dc_resize_600_jpg": check_d16c99dc_resize_600_jpg,
    "check_d16c99dc_duplicate_resize_rename": check_d16c99dc_duplicate_resize_rename,
    "check_d16c99dc_crop_500x500_topleft": check_d16c99dc_crop_500x500_topleft,
    "check_d16c99dc_opacity_and_layer_order": check_d16c99dc_opacity_and_layer_order,
    "check_b148e375_new_layer_circle": check_b148e375_new_layer_circle,
    "check_b148e375_duplicate_rename_hide": check_b148e375_duplicate_rename_hide,
    "check_b148e375_resize_50_percent": check_b148e375_resize_50_percent,
    "check_b148e375_rect_select_fill_red": check_b148e375_rect_select_fill_red,
    "check_554785e9_saturation_increase_40": check_554785e9_saturation_increase_40,
    "check_7767eef2_text_copyright": check_7767eef2_text_copyright,
    "check_734d6579_green_background": check_734d6579_green_background,
    # Blender evaluators
    "check_blender_object_exists": check_blender_object_exists,
    "check_blender_object_deleted": check_blender_object_deleted,
    "check_blender_object_count": check_blender_object_count,
    "check_blender_object_location": check_blender_object_location,
    "check_blender_object_scale": check_blender_object_scale,
    "check_blender_object_rotation": check_blender_object_rotation,
    "check_blender_object_renamed": check_blender_object_renamed,
    "check_blender_object_visibility": check_blender_object_visibility,
    "check_blender_light_type": check_blender_light_type,
    "check_blender_light_energy": check_blender_light_energy,
    "check_blender_render_settings": check_blender_render_settings,
    "check_blender_animation_range": check_blender_animation_range,
    "check_blender_collection_exists": check_blender_collection_exists,
    "check_blender_object_in_collection": check_blender_object_in_collection,
    "check_blender_text_content": check_blender_text_content,
    "check_blender_material_pbr": check_blender_material_pbr,
    "check_blender_modifier_boolean": check_blender_modifier_boolean,
    "check_blender_texture_assigned": check_blender_texture_assigned,
    "check_blender_modifier_stack": check_blender_modifier_stack,
    "check_blender_world_hdri": check_blender_world_hdri,
    "check_blender_animation_keyframes": check_blender_animation_keyframes,
    "check_blender_parent_child": check_blender_parent_child,
    "check_blender_collection_members": check_blender_collection_members,
    "check_blender_constraints_multi": check_blender_constraints_multi,
    "check_blender_applied_modifier": check_blender_applied_modifier,
    "check_blender_smooth_shading": check_blender_smooth_shading,
    "check_blender_particle_params": check_blender_particle_params,
    "check_blender_selective_smooth": check_blender_selective_smooth,
    "check_blender_animation_extended": check_blender_animation_extended,
    "check_blender_collection_organization": check_blender_collection_organization,
    "check_blender_hierarchy": check_blender_hierarchy,
    "check_blender_multi_light_config": check_blender_multi_light_config,
    "check_blender_text_styling": check_blender_text_styling,
    "check_blender_material_textures": check_blender_material_textures,
    "check_blender_follow_path": check_blender_follow_path,
    "check_blender_modifier_order": check_blender_modifier_order,
    "check_blender_transform_applied": check_blender_transform_applied,
    "check_blender_mesh_bounds": check_blender_mesh_bounds,
    "check_blender_render_output": check_blender_render_output,
    "check_blender_render_video": check_blender_render_video,
    "check_blender_multi_material_scene": check_blender_multi_material_scene,
    "check_blender_scene_objects": check_blender_scene_objects,
    "check_blender_material_color": check_blender_material_color,
    "check_blender_camera_config": check_blender_camera_config,
    "check_blender_modifier_subsurf": check_blender_modifier_subsurf,
    "check_blender_render_engine": check_blender_render_engine,
    "check_blender_frame_range": check_blender_frame_range,
    "check_blender_fps": check_blender_fps,
    "check_blender_mesh_modified": check_blender_mesh_modified,
    "check_blender_modifier_bevel": check_blender_modifier_bevel,
    "check_blender_pbr_setup": check_blender_pbr_setup,
}
